karl_landsteiner_name = "Karl Landsteiner Privatuniversität für Gesundheitswissenschaften Krems"
AFFILIATION_NAME_ALIASES = {
    "CEST Kompetenzzentrum fuer Elektrochemische Oberflaechentechnologie GmbH Linz": "CEST Linz",
    "Technische Universität Wien": "TU Wien",
    "BioTechMed-Graz": "BioTechMed Graz",
    "Universität Innsbruck": "Uni Innsbruck",
    "Center for Biomarker Research in Medicine (CBmed) Graz": "CBmed Graz",
    "Research Center Pharmaceutical Engineering GmbH": "RCPE GmbH",
    "Veterinärmedizinische Universität Wien": "Vetmeduni",
    "Ludwig Boltzmann Gesellschaft Wien": "LBG Wien",
    "Universität für Bodenkultur Wien": "BOKU Wien",
    "Medizinische Universität Wien": "MedUni Wien",
    "Christian Doppler Forschungsgesellschaft Wien": "CDG Wien",
    "Medizinische Universität Graz": "MedUni Graz",
    "Karl-Franzens-Universität Graz": "Uni Graz",
    "St. Anna Children's Cancer Research Institute": "St. Anna CCRI",
    "Montanuniversität Leoben": "Montanuni Leoben",
    "Technische Universität Graz": "TU Graz",
    "Universität Wien": "Uni Wien",
    "The Austrian Centre of Industrial Biotechnology Graz": "ACIB Graz",
    "Austrian Cluster for Tissue Regeneration Wien": "Austrian Cluster for Tissue Regeneration",
    "Österreichische Akademie der Wissenschaften Graz": "ÖAW Graz",
    "Österreichische Akademie der Wissenschaften Innsbruck": "ÖAW Innsbruck",
    "Österreichische Akademie der Wissenschaften Wien": "ÖAW Wien",
    "Österreichische Akademie der Wissenschaften Linz": "ÖAW Linz",
    "Österreichische Akademie der Wissenschaften Leoben": "ÖAW Leoben",
    "Johannes Kepler Universität Linz": "JKU Linz",
    "Paracelsus Medizinische Privatuniversität": "PMU",
    "Sigmund Freud Privatuniversität": "Sigmund Freud Privatuniversität Wien",
    karl_landsteiner_name: "KL (Karl Landsteiner)",
    "Paris-Lodron-Universität Salzburg": "PLUS",
    "Karl Landsteiner Gesellschaft Wien": "Karl Landsteiner Gesellschaft (KLG)",
    "Medizinische Universität Innsbruck": "MedUni Innsbruck",
    "Austrian Institute of Technology Wien": "AIT Wien",
    "Computer Algorithms for Medicine Laboratory (Café-Lab)": "Café-Lab",
    "Research Institute of Molecular Pathology, Vienna": "IMP Vienna",
    "Institute of Science and Technology Austria (ISTA)": "ISTA",
    "Ionicon Analytik GmbH": "Ionicon Analytik GmbH",
    "Vienna Institute for Nature Conservation & Analysis (VINCA)": "VINCA",
    "Austrian Society of Gastroenterology and Hepatology (OEGGH)": "ÖGGH",
    "Environment Agency Austria": "UBA",
    "Wolf Science Center": "Wolf Science Center",
    "Austrian Polar Research Institute": "APRI",
    "Wittgenstein Center Wien": "Wittgenstein Centre",
    "Complexity Science Hub Vienna": "CSH Wien",
    "WasserCluster Lunz": "WasserCluster Lunz",
    "FFoQSI GmbH-Austrian Competence Centre for Feed and Food Quality": "FFoQSI GmbH",
    "BioTechMed Graz": "BioTechMed Graz",
    "Wirtschaftsuniversität Wien": "WU Wien",
    "Research Cluster Translational Cancer Therapy Research": "RCT Cancer Therapy",
}
